table Episodes
	lineageTag: aab1697b-b6b2-46f4-81a4-d7e900cfab5a

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 0937bc8f-a66c-410b-8d96-9e025d51fe7d
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 4fb8ddb3-5b00-40dd-a3ed-6bbd9f63350a
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column 'Created at'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd5aede4-c21a-4781-9906-fceddae07ece
		summarizeBy: none
		sourceColumn: Created at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Course ID'
		dataType: int64
		formatString: 0
		lineageTag: 42c1dd2a-6609-459b-add7-488752640483
		summarizeBy: none
		sourceColumn: Course ID

		annotation SummarizationSetBy = Automatic

	column 'Course Name'
		dataType: string
		lineageTag: 4fd18843-9280-4596-808e-3960bd50e02e
		summarizeBy: none
		sourceColumn: Course Name

		annotation SummarizationSetBy = Automatic

	partition Episodes = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\v-krb\OneDrive\Power BI portfolio\UPWORK\Data Visualisation\export_69145465bb687.xlsx"), null, true),
				    Episodes_Sheet = Source{[Item="Episodes",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Episodes_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Title", type text}, {"Created at", type datetime}, {"Course ID", Int64.Type}, {"Course Name", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Errors",{{"Created at", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

