table DimDate
	lineageTag: 46fd74e3-329d-4a0e-ba3c-33804932d421

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: bb3f6825-c81e-4e9f-a677-7ab00931dce1
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: a2ba2480-1e1c-407b-a8d4-46a7b71943a6
			defaultHierarchy: LocalDateTable_378928ee-30e0-4719-896f-a92541e2704e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 247b11e8-4183-4fa3-971e-f1842be49e90
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 3683982b-a0b6-49f0-b68d-cd9798277ad6
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: 77e88c40-8ee5-49c6-9a64-d78b926dff9d
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Short'
		dataType: string
		lineageTag: 7e3144ae-4959-4dfc-bcc4-43e00640dc98
		summarizeBy: none
		sourceColumn: Month Short

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 13190d25-cb40-4ba3-bad7-ec4eddf81d6b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: 819da27d-e87b-4240-929a-ead500535b3b
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = User

	column Day
		dataType: int64
		formatString: 0
		lineageTag: bef5483e-2f34-4719-b523-23ce4fdf4d92
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = User

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: e2f11a4d-b7bc-4ce5-a614-39d3599f52ff
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = User

	column 'Day Name'
		dataType: string
		lineageTag: 5339ae40-548e-48cf-b20e-dcdabfb84de8
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		dataType: string
		lineageTag: f8a081e7-ad8a-4515-8ed0-115433117628
		summarizeBy: none
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	column 'Month Sort'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a96b4cb2-70cf-4dec-9800-9c092c7c5175
		summarizeBy: sum
		sourceColumn: Month Sort

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		source =
				let
				    StartDate = #date(2014, 1, 1),
				    EndDate = #date(2017, 12, 31),
				    DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
				
				    AddYear = Table.AddColumn(DateTable, "Year", each Date.Year([Date]), Int64.Type),
				    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
				    AddMonthName = Table.AddColumn(AddMonth, "Month Name", each Date.ToText([Date], "MMMM")),
				    AddMonthShort = Table.AddColumn(AddMonthName, "Month Short", each Date.ToText([Date], "MMM")),
				
				    // Add Month Sort column for proper sorting
				    AddMonthSort = Table.AddColumn(AddMonthShort, "Month Sort", each Date.Month([Date]), Int64.Type),
				
				    AddQuarter = Table.AddColumn(AddMonthSort, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    AddDay = Table.AddColumn(AddQuarter, "Day", each Date.Day([Date]), Int64.Type),
				    AddDayOfWeek = Table.AddColumn(AddDay, "Day of Week", each Date.DayOfWeek([Date]), Int64.Type),
				    AddDayName = Table.AddColumn(AddDayOfWeek, "Day Name", each Date.ToText([Date], "dddd")),
				    AddWeek = Table.AddColumn(AddDayName, "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
				    AddIsWeekend = Table.AddColumn(AddWeek, "Is Weekend", each if Date.DayOfWeek([Date]) >= 5 then "Yes" else "No"),
				
				    ReorderColumns = Table.ReorderColumns(AddIsWeekend, {
				        "Date", "Year", "Month", "Month Name", "Month Short", "Month Sort", "Quarter", "Week of Year",
				        "Day", "Day of Week", "Day Name", "Is Weekend"
				    }),
				
				    SetTypes = Table.TransformColumnTypes(ReorderColumns, {
				        {"Date", type date},
				        {"Year", Int64.Type},
				        {"Month", Int64.Type},
				        {"Month Name", type text},
				        {"Month Short", type text},
				        {"Month Sort", Int64.Type},
				        {"Quarter", type text},
				        {"Week of Year", Int64.Type},
				        {"Day", Int64.Type},
				        {"Day of Week", Int64.Type},
				        {"Day Name", type text},
				        {"Is Weekend", type text}
				    })
				in
				    SetTypes

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

