table DimRegion
	lineageTag: 75a7a5b9-1fa1-427a-968c-cdb480b2b85a

	column City
		dataType: string
		lineageTag: ff60d71c-3b2e-4611-8e84-c35e2ed5ad71
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 05952059-d4b6-4a48-a48d-8fd6866152b1
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 4dff3386-fc69-4b26-9eb3-167a9c3e66f8
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: string
		lineageTag: ce755a67-3a08-44c7-a64e-f6dc41abffd1
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	partition DimRegion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\v-krb\OneDrive\Power BI portfolio\Superstore sales dashboard\Sample - Superstore.csv"),[Delimiter=",", Columns=21, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"City", "State", "Region"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Custom" = Table.AddColumn(#"Removed Duplicates", "RegionID", each [Region] & "_" & [State]& "_" & [City])
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

